export {default as Header} from './header/Header'
export {default as Cryptocurrencies} from './cryptocurrencies/Cryptocurrencies'
export {default as News} from './news/News'
export {default as Homepage} from './homepage/Homepage'
export {default as CryptoDetails} from './cryptodetails/CryptoDetails'